/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-17 01:49:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class idpwdSerch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../../views/common/meta.jsp", Long.valueOf(1597472488000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>NANOONDA_SERCH</title>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>NANOONDA</title>\r\n");
      out.write("<link href=\"/nnd/resources/css/basic.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/nnd/resources/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/nnd/resources/css/diarystyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/nnd/resources/css/poststyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/nnd/resources/css/adminstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/nnd/resources/css/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/nnd/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/nnd/resources/js/script.js\"></script>\r\n");
      out.write("<!--탭:js-->\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 이거 있어야 됨 관리자 사이드바 두줄 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//탭메뉴 스크립트\r\n");
      out.write("  $( function() {\r\n");
      out.write("\t$( \"#tabs\" ).tabs();\r\n");
      out.write("  } );\r\n");
      out.write("  \r\n");
      out.write("/*  function serchok(){\r\n");
      out.write("\t location.href='history.go(-1)';\r\n");
      out.write(" } */\r\n");
      out.write(" \r\n");
      out.write("//이메일 중복체크\r\n");
      out.write("\tfunction emailCheck(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"/nnd/emaildateCk\",\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdata: {email: $(\"#pwdemail\").val()},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif(data == \"ook\"){\r\n");
      out.write("\t\t\t\t\talert(\"가입하지 않은 이메일입니다. \\n 다시 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t//$(\"#pwd\").focus();\r\n");
      out.write("\t\t\t\t\t $('.btnfindpWd').attr(\"type\", \"button\");\r\n");
      out.write("\t\t\t\t\t $('.btnfindpWd').css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"가입한 이메일입니다.\");\r\n");
      out.write("\t\t\t\t\t$('.btnfindpWd').attr(\"type\", \"submit\");\r\n");
      out.write("\t\t\t\t\t$('.btnfindpWd').css(\"display\", \"block\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHP, textstatus, errorthrown){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textstatus + \", \" + errorthrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write(" \t\r\n");
      out.write("\t function emailreset() {\r\n");
      out.write("\t\t location=\"/nnd/passdateCk\";\r\n");
      out.write("\t\t //$('#pwdemail').val('sksnsek20813ekd');\r\n");
      out.write("\t }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"subWrap\">\r\n");
      out.write("\t<!--header:s-->\r\n");
      out.write("\t<div class=\"title\">\r\n");
      out.write("\t\t<span class=\"tit_logo\"><a href=\"/nnd/index.jsp\"><img src=\"/nnd/resources/images/logofix.png\"></a></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--header:e-->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<section id=\"tabs\" class=\"findWrap\">\r\n");
      out.write("\t\t<ul class=\"findTitle\">\r\n");
      out.write("\t\t\t<li><a href=\"#tabs-1\">아이디 찾기</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#tabs-2\">비밀번호 찾기</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div id=\"tabs-1\" class=\"findWrapIn\">\r\n");
      out.write("\t\t\t<strong>아이디찾기</strong>\r\n");
      out.write("\t\t\t<div class=\"emailSerch\">\r\n");
      out.write("\t\t\t\t<h3>이메일 주소로 찾기</h3>\r\n");
      out.write("\t\t\t\t<div class=\"cont\">\r\n");
      out.write("\t\t\t\t\t<div class=\"contTop\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"/nnd/searchid\" method=\"post\" class=\"nameform_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pwdput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>이메일 입력</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>회원가입시 인증된 이메일로 입력해 주세요.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fminput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"email\" class=\"blind\">이메일</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"email\" type=\"text\" class=\"email\" name=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"pwdput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>비밀 번호 입력</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>비밀 번호를 입력해 주세요.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pwdinput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"pwd\" class=\"blind\">비밀 번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"pwd\" type=\"password\" class=\"pwd\" name=\"\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btnfindpWd\">아이디 찾기</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"tabs-2\" class=\"findWrapIn\">\r\n");
      out.write("         <strong>비밀번호 찾기</strong>\r\n");
      out.write("         <div class=\"emailSerch\">\r\n");
      out.write("            <h3>이메일 주소로 찾기</h3>\r\n");
      out.write("            <div class=\"cont\">\r\n");
      out.write("               <div class=\"contTop\">\r\n");
      out.write("                  <h4>이메일 주소 입력</h4>\r\n");
      out.write("                  <p>회원가입시 인증된 아이디 / 이메일로 입력해 주세요.</p>\r\n");
      out.write("                  <form action=\"/nnd/mresetpwd\" class=\"emailform_wrap\" method=\"post\">\r\n");
      out.write("                  <!-- <form action=\"/nnd/views/email/searchPw.jsp\" class=\"emailform_wrap\" method=\"post\"> -->\r\n");
      out.write("                     <legend class=\"blind\">아이디 입력</legend>\r\n");
      out.write("                     <div class=\"fminput\">\r\n");
      out.write("                        <label for=\"findEmail\" class=\"blind\">아이디</label>\r\n");
      out.write("                        <input id=\"\" type=\"text\" class=\"findEmail\" name=\"id\" placeholder=\"아이디를 입력해주세요\">\r\n");
      out.write("                        <!-- <input type=\"button\" id=\"emailckbtn\" value=\"중복체크\" onclick=\"\"></td> -->\r\n");
      out.write("                     </div>\r\n");
      out.write("                     \r\n");
      out.write("                     <legend class=\"blind\">이메일 주소 입력</legend>\r\n");
      out.write("                     <div class=\"fminput\">\r\n");
      out.write("                        <label for=\"findEmail\" class=\"blind\">이메일 주소</label>\r\n");
      out.write("                        <input id=\"pwdemail\" type=\"text\" class=\"findEmail\" name=\"email\" placeholder=\"이메일을 입력해주세요\">\r\n");
      out.write("                        <!-- <input type=\"button\" id=\"emailckbtn\" value=\"중복체크\" onclick=\"return emailCheck();\"> --></td>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"txtBox\">\r\n");
      out.write("                        <span>\r\n");
      out.write("                           비밀번호는 회원가입시 가입하신 이메일로 보내드립니다.<br>\r\n");
      out.write("                           이메일이 생각나지 않을 경우 문의 주세요\r\n");
      out.write("                        </span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <button type=\"submit\" class=\"btnfindpWd\" >비밀번호 찾기</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--findWrap:e-->\r\n");
      out.write("</div>\r\n");
      out.write("<!--subWrap:e-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
