----------------------------------------------------------------------------------- MEMBER (회원)
DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
 ID VARCHAR2(15) PRIMARY KEY,
 PWD VARCHAR2(15) NOT NULL,
 EMAIL VARCHAR2(30) NOT NULL UNIQUE,
 EMAILAUTH CHAR(1)  DEFAULT 'N',
 NNAME VARCHAR2(20) NOT NULL UNIQUE,
 MEMBER_NO NUMBER,
 ENROLL_DATE DATE DEFAULT SYSDATE,
 LASTMODIFIED DATE, --마지막 비밀번호 수정일
 DC_COUNT NUMBER DEFAULT 0, --신고 받은 횟수
 LOGIN_LIMIT CHAR(1)  DEFAULT 'N', -- (Y: 로그인제한, N: 로그인가능)
 STATUS CHAR(1) DEFAULT '1',   --(1: 일반회원, 2: 최고관리자, 3: 일반관리자, 4: 휴면회원)
CHECK(STATUS IN (1,2,3,4)),
CHECK (LOGIN_LIMIT IN('Y','N') )

);
--멤버 코멘트
COMMENT ON COLUMN MEMBER.ID IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.EMAILAUTH IS '이메일확인';
COMMENT ON COLUMN MEMBER.NNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.LASTMODIFIED IS '비밀번호수정일';
COMMENT ON COLUMN MEMBER.DC_COUNT IS '신고건수';
COMMENT ON COLUMN MEMBER.LOGIN_LIMIT IS '로그인제한';
COMMENT ON COLUMN MEMBER.STATUS IS '회원상태';

--회원번호 시퀀스
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

INSERT INTO MEMBER VALUES('admin01','1234','kkk21@iei.or.kr',DEFAULT,'관리자1',MEMBER_SEQ.NEXTVAL,'2019-01-01','2020-01-01',0,'N',3);
INSERT INTO MEMBER VALUES('admin02','2345','jjj12@iei.or.kr',DEFAULT,'관리자2',MEMBER_SEQ.NEXTVAL,'2019-01-01','2020-01-01',0,'N',2);
INSERT INTO MEMBER VALUES('user11','pass11','top99@naver.com',DEFAULT,'피치',MEMBER_SEQ.NEXTVAL,'2020-01-01','2020-01-05',1,'N',1);
INSERT INTO MEMBER VALUES('user22','pass22','kang05@daum.net',DEFAULT,'데이지',MEMBER_SEQ.NEXTVAL,'2020-01-01','2020-01-05',0,'N',4);
INSERT INTO MEMBER VALUES('user33','pass33','postno22@naver.com',DEFAULT,'릴리',MEMBER_SEQ.NEXTVAL,'2020-01-01','2020-02-06',2,'N',1);
INSERT INTO MEMBER VALUES('user44','pass44','coffeegood@naver.com',DEFAULT,'머큐리',MEMBER_SEQ.NEXTVAL,'2020-01-01','2020-02-06',0,'N',4);
INSERT INTO MEMBER VALUES('user55','pass55','utut55@daum.net',DEFAULT,'피카츄',MEMBER_SEQ.NEXTVAL,'2020-02-01','2020-03-13',2,'N',1);
INSERT INTO MEMBER VALUES('user66','pass66','lovelove6@naver.com',DEFAULT,'쥬피터',MEMBER_SEQ.NEXTVAL,'2020-02-01','2020-04-10',5,'Y',1);
INSERT INTO MEMBER VALUES('user77','pass77','luckyman01@naver.com',DEFAULT,'세일러문',MEMBER_SEQ.NEXTVAL,'2020-02-01','2020-04-22',0,'N',1);
INSERT INTO MEMBER VALUES('user88','pass88','tbspen8@daum.net',DEFAULT,'라이츄',MEMBER_SEQ.NEXTVAL,'2020-02-01','2020-05-03',3,'N',1);
INSERT INTO MEMBER VALUES('user99','pass99','gogosing@naver.com',DEFAULT,'파이리',MEMBER_SEQ.NEXTVAL,'2020-02-01','2020-05-18',0,'N',1);
INSERT INTO MEMBER VALUES('user111','pass111','top999@naver.com',DEFAULT,'꼬부기',MEMBER_SEQ.NEXTVAL,'2020-03-01','2020-06-30',0,'N',1);
INSERT INTO MEMBER VALUES('user222','pass222','kang0505@daum.net',DEFAULT,'버터풀',MEMBER_SEQ.NEXTVAL,'2020-03-01','2020-07-02',5,'Y',1);
INSERT INTO MEMBER VALUES('user333','pass333','postno222@naver.com',DEFAULT,'야도란',MEMBER_SEQ.NEXTVAL,'2020-03-01','2020-07-10',0,'N',1);
INSERT INTO MEMBER VALUES('user444','pass444','coffeegooood@naver.com',DEFAULT,'피존투',MEMBER_SEQ.NEXTVAL,'2020-04-01','2020-07-17',1,'N',1);
INSERT INTO MEMBER VALUES('user555','pass555','utut555@daum.net',DEFAULT,'잠만보',MEMBER_SEQ.NEXTVAL,'2020-04-01','2020-07-22',0,'N',1);
INSERT INTO MEMBER VALUES('user666','pass666','lovelove66@naver.com',DEFAULT,'키티',MEMBER_SEQ.NEXTVAL,'2020-04-01','2020-08-01',1,'N',1);
INSERT INTO MEMBER VALUES('user777','pass777','luckyman0101@naver.com',DEFAULT,'미피',MEMBER_SEQ.NEXTVAL,'2020-05-01','2020-08-03',0,'N',1);
INSERT INTO MEMBER VALUES('user888','pass888','tbspen88@daum.net',DEFAULT,'용가리',MEMBER_SEQ.NEXTVAL,'2020-05-01','2020-08-09',1,'N',1);
INSERT INTO MEMBER VALUES('user999','pass999','gogogosing@naver.com',DEFAULT,'징징이',MEMBER_SEQ.NEXTVAL,'2020-05-01','2020-08-11',0,'N',1);

COMMIT;


----------------------------------------------------------------------------------- DIARY (오픈다이어리)
DROP TABLE DIARY CASCADE CONSTRAINTS;

CREATE TABLE DIARY(
 DIARY_NO NUMBER PRIMARY KEY,
 DIARY_TITLE VARCHAR2(50) NOT NULL,
 DIARY_CONTENT VARCHAR2(2000) NOT NULL,
 DIARY_WRITER VARCHAR2(20) NOT NULL,
 DIARY_DATE DATE DEFAULT SYSDATE,
 READ_COUNT NUMBER DEFAULT 0, 
 TEMP_OK VARCHAR2(1) DEFAULT 'N',
 OPEN_OK VARCHAR2(1) DEFAULT 'Y', 
 CHECK(TEMP_OK IN ('Y', 'N')),
 CHECK(OPEN_OK IN ('Y', 'N')),
 FOREIGN KEY(DIARY_WRITER) REFERENCES MEMBER(NNAME) ON DELETE CASCADE
);

--다이어리 코멘트
COMMENT ON COLUMN DIARY.DIARY_NO IS '일기번호';
COMMENT ON COLUMN DIARY.DIARY_TITLE IS '글제목';
COMMENT ON COLUMN DIARY.DIARY_CONTENT IS '글내용';
COMMENT ON COLUMN DIARY.DIARY_WRITER IS '작성자닉네임';
COMMENT ON COLUMN DIARY.DIARY_DATE IS '글작성일';
COMMENT ON COLUMN DIARY.READ_COUNT IS '글조회수';
COMMENT ON COLUMN DIARY.TEMP_OK IS '임시저장여부';
COMMENT ON COLUMN DIARY.OPEN_OK IS '공개여부';

--다이어리 번호 시퀀스
DROP SEQUENCE DIARY_SEQ;
CREATE SEQUENCE DIARY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

--다이어리 샘플
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'눈이 오네','너도 눈처럼 마냥 오기만 하여라','피치','2020-07-02',22,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'섬','사람들 사이에 섬이 있다. 그 섬에 가고 싶다.','릴리','2020-07-05',20,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'이 가을에','아직도 너를 사랑해서 슬프다.','머큐리','2020-07-09',20,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'회상','이제 막 자리한 눈가 주름 사이사이로 아득한 과거를 아련하게 회상해 본다','피카츄','2020-07-11',17,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'새로운 길','내를 건너서 숲으로 고개를 넘어서 마을로 어제도 가고 오늘도 갈 나의 길 새로운 길','쥬피터','2020-07-15',16,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'봄길','길이 끝난 곳에도 길이 있다.','세일러문','2020-07-20',19,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'강물의 일','사람의 일에도 눈물이 나지 않는데 강물의 일에는 눈물이 난다.','라이츄','2020-07-22',15,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'너에게 쓴다','꽃이 피었다고 너에게 쓰고 꽃이 졌다고 너에게 쓴다.','파이리','2020-07-24',11,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'저녁의 문장','당신이 없는 두 번째 저녁이 지나가고 있다.','꼬부기','2020-07-27',13,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'흔들리며 피는 꽃','흔들리지 않고 피는 꽃이 어디 있으랴','버터풀','2020-07-29',20,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'비 오는 날','하루 종일 비가 서 있고 하루 종일 나무가 서 있고.','야도란','2020-08-01',12,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'한번','아침이다. 눈을 떴다. 귀뚜라미가 운다.','피존투','2020-08-02',8,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'비가 오네','너도 비처럼 마냥 오기만 하여라','잠만보','2020-08-03',16,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'섬섬','사람들 사이에 섬이 있다. 그 섬에 가고 싶다.','키티','2020-08-05',11,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'이 여름에','아직도 너를 사랑해서 슬프다.','미피','2020-08-06',7,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'회상합니다','이제 막 자리한 눈가 주름 사이사이로 아득한 과거를 아련하게 회상해 본다','용가리','2020-08-08',5,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'뉴로드','내를 건너서 숲으로 고개를 넘어서 마을로 어제도 가고 오늘도 갈 나의 길 새로운 길','징징이','2020-08-09',4,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'스프링','길이 끝난 곳에도 길이 있다.','키티','2020-08-11',2,DEFAULT,'Y');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'장마','비가 너무 많이 와요.','피치','2020-08-21',3,DEFAULT,'Y');

--다이어리 임시저장 샘플
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'눈눈','너도 눈처럼 마냥 오기만 하여라','피치','2020-07-02',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'섬마을','사람들 사이에 섬이 있다. 그 섬에 가고 싶다.','데이지','2020-07-03',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'이 겨울','아직도 너를 사랑해서 슬프다.','릴리','2020-07-04',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'애상','이제 막 자리한 눈가 주름 사이사이로 아득한 과거를 아련하게 회상해 본다','머큐리','2020-07-05',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'새 길','내를 건너서 숲으로 고개를 넘어서 마을로 어제도 가고 오늘도 갈 나의 길 새로운 길','피카츄','2020-07-07',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'봄봄봄','길이 끝난 곳에도 길이 있다.','라이츄','2020-07-09',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'강물','사람의 일에도 눈물이 나지 않는데 강물의 일에는 눈물이 난다.','파이리','2020-07-17',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'너에게','꽃이 피었다고 너에게 쓰고 꽃이 졌다고 너에게 쓴다.','꼬부기','2020-07-20',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'저녁','당신이 없는 두 번째 저녁이 지나가고 있다.','버터풀','2020-07-25',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'흔들린다','흔들리지 않고 피는 꽃이 어디 있으랴','야도란','2020-07-27',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'비가 와요','하루 종일 비가 서 있고 하루 종일 나무가 서 있고.','피존투','2020-07-30',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'한번만','아침이다. 눈을 떴다. 귀뚜라미가 운다.','잠만보','2020-08-01',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'눈이..','너도 눈처럼 마냥 오기만 하여라','키티','2020-08-02',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'또','사람들 사이에 섬이 있다. 그 섬에 가고 싶다.','쥬피터','2020-08-03',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'이번','아직도 너를 사랑해서 슬프다.','세일러문','2020-08-03',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'상상','이제 막 자리한 눈가 주름 사이사이로 아득한 과거를 아련하게 회상해 본다','용가리','2020-08-05',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'길을','내를 건너서 숲으로 고개를 넘어서 마을로 어제도 가고 오늘도 갈 나의 길 새로운 길','징징이','2020-08-06',DEFAULT,'Y',DEFAULT);
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'여름이 길다','길이 끝난 곳에도 길이 있다.','미피','2020-08-10',DEFAULT,'Y',DEFAULT);

--마이다이어리 저장 샘플
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'울릉도','너도 눈처럼 마냥 오기만 하여라','피치','2020-07-01',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'독도는 우리땅','사람들 사이에 섬이 있다. 그 섬에 가고 싶다.','릴리','2020-07-03',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'이럴수가','아직도 너를 사랑해서 슬프다.','머큐리','2020-07-10',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'회 먹고싶다','이제 막 자리한 눈가 주름 사이사이로 아득한 과거를 아련하게 회상해 본다','피카츄','2020-07-15',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'새가 울어요','내를 건너서 숲으로 고개를 넘어서 마을로 어제도 가고 오늘도 갈 나의 길 새로운 길','쥬피터','2020-07-17',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'봄','길이 끝난 곳에도 길이 있다.','세일러문','2020-07-22',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'냇물','사람의 일에도 눈물이 나지 않는데 강물의 일에는 눈물이 난다.','라이츄','2020-07-25',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'나에게','꽃이 피었다고 너에게 쓰고 꽃이 졌다고 너에게 쓴다.','파이리','2020-07-27',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'오늘 아침','당신이 없는 두 번째 저녁이 지나가고 있다.','꼬부기','2020-07-29',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'춤추는','흔들리지 않고 피는 꽃이 어디 있으랴','버터풀','2020-07-31',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'꿈꾼다','하루 종일 비가 서 있고 하루 종일 나무가 서 있고.','야도란','2020-08-02',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'또','아침이다. 눈을 떴다. 귀뚜라미가 운다.','피존투','2020-08-05',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'비','너도 비처럼 마냥 오기만 하여라','잠만보','2020-08-06',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'장마가 안끝나','사람들 사이에 섬이 있다. 그 섬에 가고 싶다.','키티','2020-08-07',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'아직 더워','아직도 너를 사랑해서 슬프다.','미피','2020-08-08',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'배고파','이제 막 자리한 눈가 주름 사이사이로 아득한 과거를 아련하게 회상해 본다','용가리','2020-08-09',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'졸려요','내를 건너서 숲으로 고개를 넘어서 마을로 어제도 가고 오늘도 갈 나의 길 새로운 길','징징이','2020-08-10',DEFAULT,DEFAULT,'N');
INSERT INTO DIARY VALUES(DIARY_SEQ.NEXTVAL,'썸머','길이 끝난 곳에도 길이 있다.','피치','2020-08-11',DEFAULT,DEFAULT,'N');

COMMIT;


----------------------------------------------------------------------------------- REPLY (댓글)
DROP TABLE REPLY CASCADE CONSTRAINTS;

CREATE TABLE REPLY(
 REPLY_NO NUMBER PRIMARY KEY,
 DIARY_NO NUMBER NOT NULL,
 REPLY_CONTENT VARCHAR2(500) NOT NULL,
 REPLY_WRITER VARCHAR2(20) NOT NULL,
 REPLY_DATE DATE DEFAULT SYSDATE,
 ALARM_OK VARCHAR2(1) DEFAULT 'Y',
 CHECK(ALARM_OK IN ('Y', 'N')),
 FOREIGN KEY(REPLY_WRITER) REFERENCES MEMBER(NNAME) ON DELETE CASCADE,
 FOREIGN KEY(DIARY_NO) REFERENCES DIARY(DIARY_NO) ON DELETE CASCADE
);

--댓글 코멘트
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.DIARY_NO IS '원글번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.REPLY_WRITER IS '댓글작성자닉네임';
COMMENT ON COLUMN REPLY.REPLY_DATE IS '댓글작성일';
COMMENT ON COLUMN REPLY.ALARM_OK IS '알림여부';

-- 댓글번호 시퀀스
DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,1,'좋은 글입니다.','릴리','2020-07-03',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,2,'저도 가고 싶네요.','머큐리','2020-07-05',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,3,'공감합니다.','피카츄','2020-07-10',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,4,'슬퍼요.','쥬피터','2020-07-12',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,5,'화이팅!!','세일러문','2020-07-15',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,6,'열심히 합시다~','라이츄','2020-07-22',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,7,'좋은 글입니다.','파이리','2020-07-22',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,8,'저도 가고 싶네요.','꼬부기','2020-07-25',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,9,'공감합니다.','버터풀','2020-07-27',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,10,'슬퍼요.','야도란','2020-07-30',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,11,'화이팅!!','피존투','2020-08-01',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,12,'열심히 합시다~','잠만보','2020-08-03',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,13,'좋은 글입니다.','키티','2020-08-06',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,13,'좋은 글입니다.','징징이','2020-08-06',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,14,'저도 가고 싶네요.','미피','2020-08-06',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,14,'저도 가고 싶네요.','용가리','2020-08-06',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,15,'공감합니다.','용가리','2020-08-06',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,15,'매우 공감합니다.','잠만보','2020-08-06',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,16,'슬퍼요.','징징이','2020-08-08',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,16,'저도 슬퍼요.','키티','2020-08-09',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,17,'화이팅!!','피치','2020-08-10',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,17,'공감공감~','피존투','2020-08-11',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,18,'열심히 합시다~','피치','2020-08-12',DEFAULT);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL,18,'좋은 글입니다.','야도란','2020-08-12',DEFAULT);

COMMIT;


----------------------------------------------------------------------------------- LIKECHECK / HATECHECK (댓글좋아요/싫어요)
DROP TABLE LIKECHECK CASCADE CONSTRAINTS;
DROP TABLE HATECHECK CASCADE CONSTRAINTS;

CREATE TABLE LIKECHECK (
    REPLY_NO NUMBER,
    LIKE_COUNTER VARCHAR2(15),
    LIKE_COUNT NUMBER,
    FOREIGN KEY(REPLY_NO) REFERENCES REPLY(REPLY_NO) ON DELETE CASCADE,
    FOREIGN KEY(LIKE_COUNTER) REFERENCES MEMBER(ID) ON DELETE CASCADE
);

CREATE TABLE HATECHECK (
    REPLY_NO NUMBER,
    HATE_COUNTER VARCHAR2(15),
    HATE_COUNT NUMBER,
    FOREIGN KEY(REPLY_NO) REFERENCES REPLY(REPLY_NO) ON DELETE CASCADE,
    FOREIGN KEY(HATE_COUNTER) REFERENCES MEMBER(ID) ON DELETE CASCADE
);


----------------------------------------------------------------------------------- POST (우편함)
DROP TABLE POST CASCADE CONSTRAINTS;

CREATE TABLE POST(
POST_NO NUMBER PRIMARY KEY,
POST_SENDER VARCHAR2(20) NOT NULL,
POST_RECEIVER VARCHAR2(20) NOT NULL,
POST_TITLE VARCHAR2(100) NOT NULL,
POST_CONTENT VARCHAR2(4000) NOT NULL,
POST_FILE VARCHAR2(100),
POST_REFILE VARCHAR2(100),
SEND_DATE DATE DEFAULT SYSDATE,
READ_CHECK NUMBER DEFAULT '1', --안읽음 '1', 읽음 '2이상' 
SEND_DEL_CHECK CHAR(1)  DEFAULT 'N' CONSTRAINT SDCHK CHECK (SEND_DEL_CHECK IN ('Y','N')), --보낸편지함에서 지움 'Y' , 안지움 'N'
RECEIVE_DEL_CHECK CHAR(1)  DEFAULT 'N' CONSTRAINT RDCHK CHECK (RECEIVE_DEL_CHECK IN ('Y','N')), --받은편지함에서 지움 'Y' , 안지움 'N'
SAVE_CHECK CHAR(1)  DEFAULT 'N' CONSTRAINT SCHK CHECK (SAVE_CHECK IN ('Y','N')), --임시저장 'Y' , 임시저장안함 'N'
CONSTRAINT FK_S FOREIGN KEY(POST_SENDER) REFERENCES MEMBER(NNAME) ON DELETE SET NULL,
CONSTRAINT FK_R FOREIGN KEY(POST_RECEIVER) REFERENCES MEMBER(NNAME) ON DELETE SET NULL  
);

--POST 코멘트
COMMENT ON COLUMN POST.POST_NO IS '편지번호';
COMMENT ON COLUMN POST.POST_SENDER IS '보낸사람';
COMMENT ON COLUMN POST.POST_RECEIVER IS '받는사람';
COMMENT ON COLUMN POST.POST_TITLE IS '편지제목';
COMMENT ON COLUMN POST.POST_CONTENT IS '편지내용';
COMMENT ON COLUMN POST.POST_FILE IS '편지첨부파일';
COMMENT ON COLUMN POST.POST_REFILE IS '편지다운파일';
COMMENT ON COLUMN POST.SEND_DATE IS '보낸날짜';
COMMENT ON COLUMN POST.READ_CHECK IS '읽음여부';
COMMENT ON COLUMN POST.SEND_DEL_CHECK IS '보낸편지함에서삭제여부';
COMMENT ON COLUMN POST.RECEIVE_DEL_CHECK IS '받은편지함에서삭제여부';
COMMENT ON COLUMN POST.SAVE_CHECK IS '임시저장여부';

--POST_NO 시퀀스
DROP SEQUENCE POST_SEQ;
CREATE SEQUENCE POST_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;


--POST 샘플데이터
INSERT INTO POST (POST_NO, POST_SENDER, POST_RECEIVER, POST_TITLE, POST_CONTENT, SEND_DATE)
VALUES(POST_SEQ.NEXTVAL, '피치', '꼬부기', '안녕하세요', '지금은새벽2시30분', DEFAULT);
INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, '라이츄', '피치', '감성글', '감성글 쓰기에 딱 좋은 시간이네요',NULL, NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT); 
INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, '키티', 
(SELECT * FROM(
                        SELECT NNAME
                        FROM MEMBER
                        WHERE NNAME NOT LIKE '관리자%'
                        ORDER BY DBMS_RANDOM.VALUE
                        )
                        WHERE ROWNUM <=1), '일촌', '세미프로젝트', NULL,NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);        
INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, '릴리', 
(SELECT * FROM(
                        SELECT NNAME
                        FROM MEMBER
                        WHERE NNAME NOT LIKE '관리자%'
                        ORDER BY DBMS_RANDOM.VALUE
                        )
                        WHERE ROWNUM <=1), '신기하다', '보내는사람을 랜덤하게 설정 할 수가 있네요 ',NULL, NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT, 'Y'); 
INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, '머큐리', 
(SELECT * FROM(
                        SELECT NNAME
                        FROM MEMBER
                        WHERE NNAME NOT LIKE '관리자%'
                        ORDER BY DBMS_RANDOM.VALUE
                        )
                        WHERE ROWNUM <=1), '졸리다', '이제 자야지 !', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT, 'Y');       
INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, '피존투', 
(SELECT * FROM(
                        SELECT NNAME
                        FROM MEMBER
                        WHERE NNAME NOT LIKE '관리자%'
                        ORDER BY DBMS_RANDOM.VALUE
                        )
                        WHERE ROWNUM <=1), '병신', '멍청이 병신새끼', NULL, NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT, 'Y');

INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, '잠만보', (
			SELECT * FROM ( 
			SELECT NNAME FROM MEMBER WHERE STATUS='1' AND NNAME NOT IN '유저7' ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <=1 ), 
			'쿼리', '오라클쿼리쿼리랜덤쿼리', NULL, NULL, SYSTIMESTAMP, DEFAULT, DEFAULT, DEFAULT, 'N');


COMMIT;


----------------------------------------------------------------------------------- REPORT (신고게시판)
DROP TABLE REPORT CASCADE CONSTRAINTS;
CREATE TABLE REPORT (
    REPORT_NO NUMBER PRIMARY KEY,
    REPORT_STATUS CHAR(1) DEFAULT '0', --( 0: 미처리, 1: 처리, 2: 처리중)
    REPORT_TITLE VARCHAR2(50) DEFAULT '신고합니다',
    REPORT_CONTENT VARCHAR2(500),
    SENDER_NNAME VARCHAR2(20),
    RECEIVER_NNAME VARCHAR2(20),
    REPORT_REG_DATE DATE DEFAULT SYSDATE,
    REPORT_COM_DATE DATE,
    REPORT_TYPE CHAR(1),--(1 : 일기장, 2: 우편함)
    DIARY_NO NUMBER,
    POST_NO NUMBER,
    FOREIGN KEY(SENDER_NNAME) REFERENCES MEMBER(NNAME) ON DELETE CASCADE,
    FOREIGN KEY(RECEIVER_NNAME) REFERENCES MEMBER(NNAME) ON DELETE CASCADE,
    FOREIGN KEY(DIARY_NO) REFERENCES DIARY ON DELETE CASCADE,
    FOREIGN KEY(POST_NO) REFERENCES POST ON DELETE CASCADE,
    CHECK(REPORT_STATUS IN('0','1','2')),
    CHECK(REPORT_TYPE IN('1','2'))    
);

--신고게시판 코멘트
COMMENT ON COLUMN REPORT.REPORT_NO IS '신고번호';
COMMENT ON COLUMN REPORT.REPORT_STATUS IS '신고처리상태';
COMMENT ON COLUMN REPORT.REPORT_TITLE IS '신고제목';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';
COMMENT ON COLUMN REPORT.SENDER_NNAME IS '신고자닉네임';
COMMENT ON COLUMN REPORT.RECEIVER_NNAME IS '신고대상자닉네임';
COMMENT ON COLUMN REPORT.REPORT_REG_DATE IS '신고접수일';
COMMENT ON COLUMN REPORT.REPORT_COM_DATE IS '신고처리일';
COMMENT ON COLUMN REPORT.REPORT_TYPE IS '신고된게시판종류';
COMMENT ON COLUMN REPORT.DIARY_NO IS '일기장글번호';
COMMENT ON COLUMN REPORT.POST_NO IS '우편함글번호';

--신고번호 시퀀스
DROP SEQUENCE REPORT_SEQ;
CREATE SEQUENCE REPORT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

--신고 글
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL,0,'이런 글이 있어도 되나요?','관리자님 조치 좀 취해 주세요','릴리','머큐리','2020-07-11',null,1,3,null);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL,0,'진짜 기분 나쁘네요','없던 주름도 생길거 같아요','데이지','쥬피터','2020-07-20',null,1,5,null);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL,0,'어떻게 좀 해주세요','징그러워요','피카츄','세일러문','2020-07-25',null,1,6,null);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL,0,'나니??','난다고레','파이리','미피','2020-08-08',null,1,15,NULL);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL,0,'이런글을 쓰다니','기분 너무 나빠요','피치','머큐리',default,null,2,NULL,5);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL,0,'이게 뭐죠?','기분 나빠요!!','피카츄','피존투',default,null,2,NULL,6);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL,0,'이상한 편지가 왔어요','처리 좀 해주세요','라이츄','잠만보',default,null,2,NULL,7);

COMMIT;


----------------------------------------------------------------------------------- PRO (금지어)
DROP TABLE PRO CASCADE CONSTRAINTS;
CREATE TABLE PRO (
    PRO_NO NUMBER PRIMARY KEY,
    PRO_CONTENT VARCHAR2(100) NOT NULL,
    ADMIN_NNAME VARCHAR2(20),
    PRO_DATE DATE DEFAULT SYSDATE,
    REPORT_NO NUMBER,
    FOREIGN KEY(ADMIN_NNAME) REFERENCES MEMBER(NNAME) ON DELETE SET NULL,
    FOREIGN KEY(REPORT_NO) REFERENCES REPORT ON DELETE SET NULL  
);

--금지어 코멘트
COMMENT ON COLUMN PRO.PRO_NO IS '금지어번호';
COMMENT ON COLUMN PRO.PRO_CONTENT IS '금지어 내용';
COMMENT ON COLUMN PRO.ADMIN_NNAME IS '작성자';
COMMENT ON COLUMN PRO.PRO_DATE IS '등록날짜';
COMMENT ON COLUMN PRO.REPORT_NO IS '신고번호';

--금지어 시퀀스
DROP SEQUENCE PRO_SEQ;
CREATE SEQUENCE PRO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

--금지어 샘플데이터
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'개새끼','관리자1',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'미친놈','관리자1',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'지랄','관리자1',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'씨발','관리자2',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'병신','관리자1',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'샹','관리자1',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'시발','관리자1',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'ㅅㅂ','관리자2',DEFAULT,NULL);
INSERT INTO PRO VALUES(PRO_SEQ.NEXTVAL,'개자식','관리자1',DEFAULT,NULL);

COMMIT;


----------------------------------------------------------------------------------- STATISTICS (통계)
DROP TABLE STATISTICS CASCADE CONSTRAINTS;

CREATE TABLE STATISTICS(
REASON_QUIT CHAR(1), 
ENROLL_PATH CHAR(1),
VISITOR NUMBER NOT NULL,
VISITOR_DATE DATE DEFAULT SYSDATE NOT NULL,
CHECK(REASON_QUIT IN('1', '2', '3', '4')),
CHECK(ENROLL_PATH IN('1', '2', '3', '4'))
);

COMMENT ON COLUMN STATISTICS.REASON_QUIT IS '탈퇴이유';
COMMENT ON COLUMN STATISTICS.ENROLL_PATH IS '가입경로';
COMMENT ON COLUMN STATISTICS.VISITOR IS '방문자수';
COMMENT ON COLUMN STATISTICS.VISITOR_DATE IS '방문일';

INSERT INTO STATISTICS VALUES('1', '2', '10',DEFAULT);
INSERT INTO STATISTICS VALUES('2', '3', '12',DEFAULT);
INSERT INTO STATISTICS VALUES('3', '3', '20',DEFAULT);

COMMIT;


----------------------------------------------------------------------------------- NOTICE (공지사항)
DROP TABLE NOTICE CASCADE CONSTRAINTS;

CREATE TABLE NOTICE(
NOTICE_NO NUMBER PRIMARY KEY,
NOTICE_TITLE VARCHAR2(50) NOT NULL,
NOTICE_DATE DATE DEFAULT SYSDATE NOT NULL,
NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
ORIGINAL_FILEPATH VARCHAR2(50) NULL,
RENAME_FILEPATH VARCHAR2(50) NULL,
NNAME VARCHAR2(15) NOT NULL,
FOREIGN KEY(NNAME) REFERENCES MEMBER (NNAME) ON DELETE SET NULL
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '글번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '글제목';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '등록일';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '글내용';
COMMENT ON COLUMN NOTICE.ORIGINAL_FILEPATH IS '첨부파일';
COMMENT ON COLUMN NOTICE.RENAME_FILEPATH IS '첨부파일';
COMMENT ON COLUMN NOTICE.NNAME IS '작성자';

DROP SEQUENCE NOTICE_SEQ;

CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '악성댓글은 노', 
'2020-01-01', '안녕하세요 나눈다입니다 나눈다는 매우 감성적이고 성의 있는 장문의 글로 소통하는 클린한 공간임을 인지해주세요', NULL, DEFAULT, '관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '주의사항입니다.', '2020-01-01', 
'나눈다를 사용하시는 많은 분들이 말 못할 고민 등을 나누고, 서로에게 따뜻한 위로를 하고 있습니다. ', NULL, DEFAULT, '관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, 
'이용안내입니다.', '2020-01-01', '안녕하세요 나눈다입니다.
보다 많은 활용을 하시길 바라며 몇가지 사용방법을 안내해드립니다.
1. 달력페이지는 여러분이 쓰신 일기장 들이 일별로 정리되어 있는 곳입니다.
2. 문의사항은 여러분들의 의견을 듣고자 작은 공간을 마련하였습니다.
3. 악성댓글이나 물을 흐리는 분들을 신고리스트에 작성해주시면 저희가 확인하겠습니다.', NULL, DEFAULT, '관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '안내사항입니다', '2020-03-01', '화면이 안보인다고 당황하지 마시고 로그인 해주세요', NULL,
DEFAULT,'관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '안녕하세요', '2020-04-01', '벚꽃이 피는 따뜻한 봄이왔어요 ' , NULL, DEFAULT,'관리자2');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '감사합니다', '2020-05-08', '저희 커뮤니티를 찾아주셔서 감사합니다' , NULL, DEFAULT,'관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '긴급공지', '2020-03-01', '최근 악성글들이 많아지고 있습니다 다른 이들을 배려하는 맘이 필요해요' , 
NULL, DEFAULT,'관리자2');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '안녕하세요', '2020-01-01', '벌써 2020년입니다' , NULL, DEFAULT,'관리자2');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '안녕하세요', '2020-08-01', '날씨가 더워지고 있습니다 여러분들 건강 유의하세요' , NULL,
DEFAULT,'관리자2');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '긴급공지', '2020-03-01', 
'문의사항에 첨부파일을 넣을 수 있는 기능이 추가되었습니다 많은 활용 부탁드려요' , NULL, DEFAULT,'관리자2');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '긴급공지', '2020-03-08', '최근 몇몇의 이용자들로 인해 컴플레인이 늘어나고 있습니다 ' , 
NULL, DEFAULT,'관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '안녕하세요', '2020-09-01', '글을 쓰고 계절인 가을이 찾아왔어요' ,NULL, DEFAULT,'관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '안내사항입니다', '2020-10-01', '원하시는 기능을 알려주세요' ,NULL, DEFAULT,'관리자1');
INSERT INTO NOTICE VALUES(NOTICE_SEQ.NEXTVAL, '안녕하세요', '2019-12-31', '지난 한해동안 여러분들의 성원에 감사드립니다' , 
NULL, DEFAULT,'관리자1');

COMMIT;


----------------------------------------------------------------------------------- QNA (문의사항 원글)
DROP TABLE QNA CASCADE CONSTRAINTS;

CREATE TABLE QNA(
QNA_NO NUMBER PRIMARY KEY,
QNA_TITLE VARCHAR2(50) NOT NULL,
QNA_CONTENT VARCHAR2(3000) NOT NULL,
QNA_DATE DATE DEFAULT SYSDATE,
QNA_ORIGINAL_FILEPATH VARCHAR2(50) NULL,
QNA_RENAME_FILEPATH VARCHAR2(50) NULL,
NNAME VARCHAR2(15) NOT NULL,
QNA_ALARM CHAR(1) DEFAULT 'N',
CHECK (QNA_ALARM IN('Y','N')),
FOREIGN KEY(NNAME) REFERENCES MEMBER(NNAME) ON DELETE SET NULL
);

COMMENT ON COLUMN QNA.QNA_NO IS '글번호';
COMMENT ON COLUMN QNA.QNA_TITLE IS '글제목';
COMMENT ON COLUMN QNA.QNA_CONTENT IS '글내용';
COMMENT ON COLUMN QNA.QNA_DATE IS '등록일';
COMMENT ON COLUMN QNA.QNA_ORIGINAL_FILEPATH IS '첨부파일';
COMMENT ON COLUMN QNA.QNA_RENAME_FILEPATH IS '첨부파일';
COMMENT ON COLUMN QNA.NNAME IS '작성자';
COMMENT ON COLUMN QNA.QNA_ALARM IS '알람';

DROP SEQUENCE QNA_SEQ;

CREATE SEQUENCE QNA_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항이에요', '악성댓글로 인해 너무 화가 납니다', '2020-03-01', NULL, NULL, '피치', 'Y');
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항입니다', '신고를 하려고 하는데 어떻게 해야 할까요?', '2020-04-14', NULL, NULL, '릴리', 'Y');
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '질문입니다.', '혹시 이런 기능은 구현될까요?', '2020-05-09', NULL, NULL, '데이지', 'Y');
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '메인일기장에 배경색은 변경이 안될까요?', '2020-06-04', NULL, NULL, '피카츄', 'Y');
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '질문', '비밀번호 설정은 따로 안될까요?', '2020-06-09', NULL, NULL, '머큐리', 'Y');
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '폴더명으로 분류하고 싶습니다 ', '2020-06-17', NULL, NULL, '라이츄', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '폴더 추가 기능은 없을까요?', '2020-06-20', NULL, NULL, '파이리', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '달력에 나오는 것을 따로 리스트로 볼 수 없을까요?', '2020-06-24', NULL, NULL, '꼬부기', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '감성문구 더 추가해주세요', '2020-07-04', NULL, NULL, '야도란', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '이용하는 다른 사이트는 이런 기능이 있더라구요', '2020-07-09', NULL, NULL, '피존투', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '글자색을 좀 더 다양하게 지정할 수 없을까요?', '2020-07-14', NULL, NULL, '잠만보', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '신고할 수 있는 기준이 따로 정해져 있나요?', '2020-07-30', NULL, NULL, '피치', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '비밀번호가 기억이 안나요.', '2020-08-02', NULL, NULL, '꼬부기', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '금지어는 어떤 게 있나요??', '2020-08-05', NULL, NULL, '데이지', DEFAULT);
INSERT INTO QNA VALUES (QNA_SEQ.NEXTVAL, '문의사항', '어떤 경우 댓글이 삭제되나요?', '2020-08-07', NULL, NULL, '피치', DEFAULT);


COMMIT;


----------------------------------------------------------------------------------- QNA_REPLY (문의사항 답글)
DROP TABLE QNA_REPLY CASCADE CONSTRAINTS;

CREATE TABLE QNA_REPLY(
QNA_NO NUMBER,
REPLY_TITLE VARCHAR2(50) NOT NULL,
REPLY_CONTENT VARCHAR2(400) NOT NULL,
REPLY_DATE DATE DEFAULT SYSDATE NOT NULL,
NNAME VARCHAR2(15),
ALARM_OK CHAR(1)DEFAULT 'N'
CHECK (ALARM_OK IN('Y','N')),
FOREIGN KEY (QNA_NO) REFERENCES QNA (QNA_NO) ON DELETE SET NULL,
FOREIGN KEY (NNAME) REFERENCES MEMBER (NNAME) ON DELETE SET NULL  
);

COMMENT ON COLUMN QNA_REPLY.QNA_NO IS '글번호';
COMMENT ON COLUMN QNA_REPLY.REPLY_TITLE IS '답글제목';
COMMENT ON COLUMN QNA_REPLY.REPLY_CONTENT IS '답글내용';
COMMENT ON COLUMN QNA_REPLY.REPLY_DATE IS '등록일';
COMMENT ON COLUMN QNA_REPLY.NNAME IS '작성자';
COMMENT ON COLUMN QNA_REPLY.ALARM_OK IS '알람여부';

INSERT INTO QNA_REPLY VALUES(1, '1번 문의사항 답글입니다.', '불편을 드려 죄송합니다. 빠른 조치 후 고객님께 알려드리겠습니다.', 
'2020-03-01', '관리자1', DEFAULT);
INSERT INTO QNA_REPLY VALUES(2, '2번 문의사항 답글입니다.', '저희는 신고리스트가 따로 마련되어 있습니다. 그쪽으로 이용해주세요',
'2020-04-14', '관리자1', DEFAULT);
INSERT INTO QNA_REPLY VALUES(3, '3번 문의사항 답글입니다.', '조금만 기다려 주시면 원하시는 기능이 곧 나올 예정입니다.', 
'2020-05-09', '관리자1', DEFAULT);
INSERT INTO QNA_REPLY VALUES(4, '4번 문의사항 답글입니다.', '다음 리뉴얼 때 해당 기능을 업데이트할 수 있도록 노력하겠습니다.',
'2020-06-05', '관리자1', DEFAULT);
INSERT INTO QNA_REPLY VALUES(5, '5번 문의사항 답글입니다.', '마이페이지에서 수정하실 수 있습니다.', 
'2020-06-10', '관리자1', DEFAULT);

COMMIT;
